

# TODO: this is ugly, I know
ccflags-y += -I$(PWD)/drivers/video/ingenic_isp/t31/include

obj-$(CONFIG_INGENIC_ISP) += tx-isp-t31.o
tx-isp-t31-objs := tx-isp-module.o tx-isp-funcs.o libt31-firmware.a
