## T31 supported boards
obj-$(CONFIG_SND_ASOC_INGENIC_T31_BOARD) += t31-board.o

## X1000 Supported Boards
obj-$(CONFIG_SND_ASOC_INGENIC_X1000_BOARD) += x1000-board.o

## X2000 Supported Boards
obj-$(CONFIG_SND_ASOC_INGENIC_SEAL) += seal.o
